// <auto-generated />
namespace Job_Offers_Website.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class NewColumnToUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewColumnToUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "202111102201083_NewColumnToUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
